const myKohiOnboardingTemplate = {
  name: "MyKohi Client Onboarding",
  description:
    "Welcome to the MyKohi family! We are excited to get started. Please complete this onboarding form so we can help you grow your practice.",
  slug: "mykohi-onboarding",
  isDefault: true,
  sections: [
    {
      id: "basic-info",
      title: "Basic Information",
      description: "Tell us about your practice and primary contacts.",
      fields: [
        { id: "practiceName", type: "text", label: "Practice Name", required: true },
        {
          id: "primaryContact",
          type: "fullname",
          label: "Primary Contact",
          required: true,
          subFields: [
            { id: "firstName", label: "First Name", placeholder: "First Name" },
            { id: "lastName", label: "Last Name", placeholder: "Last Name" },
          ],
        },
        { id: "primaryEmail", type: "email", label: "Primary Contact Email", required: true, placeholder: "example@example.com" },
        { id: "primaryPhone", type: "phone", label: "Primary Contact Phone Number", required: true, placeholder: "(000) 000-0000" },
        {
          id: "secondaryContact",
          type: "fullname",
          label: "Secondary Contact",
          subFields: [
            { id: "firstName", label: "First Name", placeholder: "First Name" },
            { id: "lastName", label: "Last Name", placeholder: "Last Name" },
          ],
        },
        { id: "secondaryEmail", type: "email", label: "Secondary Contact Email", placeholder: "example@example.com" },
        { id: "secondaryPhone", type: "phone", label: "Secondary Contact Phone Number", placeholder: "(000) 000-0000" },
        {
          id: "practiceAddress",
          type: "address",
          label: "Practice Address",
          required: true,
          subFields: [
            { id: "street1", label: "Street Address", placeholder: "Street Address" },
            { id: "street2", label: "Street Address Line 2", placeholder: "Apt, Suite, etc." },
            { id: "city", label: "City", placeholder: "City" },
            { id: "state", label: "State / Province", placeholder: "State" },
            { id: "zip", label: "Postal / Zip Code", placeholder: "Zip Code" },
          ],
        },
        { id: "practiceWebsite", type: "text", label: "Practice Website", placeholder: "https://www.example.com" },
        { id: "socialMedia", type: "textarea", label: "Social Media Accounts", description: "List all social media URLs" },
      ],
    },
    {
      id: "practice-details",
      title: "Practice Details",
      description: "Tell us more about your services and operations.",
      fields: [
        {
          id: "servicesOffered",
          type: "checkbox",
          label: "Services Offered",
          options: ["Medication Management", "TMS Therapy", "Ketamine Therapy", "Psychotherapy"],
        },
        {
          id: "tmsDevice",
          type: "checkbox",
          label: "TMS Device",
          options: ["BrainsWay", "Apollo TMS", "MagStim", "NeuroStar", "MagVenture"],
          allowOther: true,
        },
        { id: "tmsDeviceOther", type: "text", label: "If Other, please specify which TMS Device" },
        {
          id: "ketamineType",
          type: "checkbox",
          label: "Type of Ketamine Treatment Offered",
          options: ["Spravato", "IV Ketamine", "IM Ketamine", "Oral Ketamine"],
        },
        { id: "targetDemographic", type: "textarea", label: "Tell us about your target demographic/audience" },
        { id: "operatingHours", type: "textarea", label: "What are your operating hours?" },
        { id: "missionStatement", type: "textarea", label: "What is your mission statement or unique value proposition?" },
        {
          id: "acceptsInsurance",
          type: "select",
          label: "Do you accept insurance?",
          options: ["Yes", "No"],
        },
        { id: "insuranceList", type: "textarea", label: "If Yes, which insurances do you accept?" },
        {
          id: "feeForService",
          type: "textarea",
          label: "What are your Fee For Service (Cash) rates for therapy, treatment, and evaluations?",
          description: "Please list your pricing for TMS, Ketamine, Medication Management, Evaluations, Sessions and any type of billable services.",
        },
      ],
    },
    {
      id: "team-info",
      title: "Team Information",
      description: "Help us understand your team structure.",
      fields: [
        { id: "locationCount", type: "text", label: "How many locations do you have?" },
        { id: "teamMemberCount", type: "text", label: "How many team members are there in your entire practice?" },
        { id: "providersList", type: "textarea", label: "Please list all the providers on your team and their title" },
        { id: "adminList", type: "textarea", label: "Please list all of the administrative members on your team and their title" },
        { id: "marketingContact", type: "textarea", label: "Who is the point of contact for all marketing related inquiries and collaboration?" },
        { id: "operationsContact", type: "textarea", label: "Who is the point of contact for all operational related inquiries and collaboration?" },
      ],
    },
    {
      id: "marketing-history",
      title: "Marketing History",
      description: "Tell us about your current and past marketing efforts.",
      fields: [
        { id: "currentMarketing", type: "textarea", label: "In a brief summary, what do your current marketing efforts look like?" },
        {
          id: "marketingSpend",
          type: "checkbox",
          label: "Which of the following marketing efforts have you spent money on in the last fiscal year?",
          options: [
            "Website Enhancements (Automations / Digital Content)",
            "SEO Ranking Improvement",
            "Google & Meta Ads Management",
            "Social Media Strategy & Content Creation",
          ],
        },
        {
          id: "effectiveMarketing",
          type: "checkbox",
          label: "Which of the following marketing efforts have been effective in generating consistent and high intent patient traffic for your practice?",
          options: [
            "Website Enhancements (Automations / Digital Content)",
            "SEO Ranking Improvement",
            "Google & Meta Ads Management",
            "Social Media Strategy & Content Creation",
          ],
        },
        {
          id: "brandGuide",
          type: "file",
          label: "Please upload your brand guide, practice logos and anything related to branding of your clinic",
        },
        {
          id: "staffPhotos",
          type: "file",
          label: "Please upload any professional photos of staff members, and any social media content (interviews, reels of patients or providers)",
        },
        {
          id: "officePhotos",
          type: "file",
          label: "Please upload any candid office photos, pictures of the lobby, the treatment room, the front of your office, your entrance, your front desk team, your providers",
        },
        {
          id: "googleVerification",
          type: "file",
          label: "Google Verification Document",
          description:
            "Google requires verification for any healthcare advertising. Upload one of: U.S. Government-Issued Business Registration (e.g., Articles of Incorporation, EIN confirmation letter) OR Proof of Business Address (e.g., utility bill, lease agreement, or business bank statement).",
        },
        {
          id: "domainHost",
          type: "checkbox",
          label: "Domain Host (where you park your website)",
          options: ["GoDaddy", "Namecheap", "Squarespace", "BlueHost", "HostGator", "Site Ground", "DreamHost"],
          allowOther: true,
        },
        { id: "domainHostOther", type: "text", label: "If you've selected other, please specify" },
        {
          id: "websiteHost",
          type: "checkbox",
          label: "Website Host (where you store your website files & images)",
          options: ["GoDaddy", "Namecheap", "Squarespace", "BlueHost", "HostGator", "Site Ground", "DreamHost"],
          allowOther: true,
        },
        { id: "websiteHostOther", type: "text", label: "If you've selected other, please specify" },
      ],
    },
    {
      id: "account-access",
      title: "Account Access",
      description: "We'll need access to some of your accounts to get started. Please provide login credentials or invite us as collaborators.",
      fields: [
        {
          id: "ehrSystem",
          type: "checkbox",
          label: "Electronic Health Record (EHR) System",
          options: ["AdvancedMD", "DrChrono", "Valant", "SimplePractice", "TherapyNotes", "Athena Health"],
          allowOther: true,
        },
        { id: "ehrOther", type: "text", label: "If Other EHR, please specify" },
        { id: "googleBusinessEmail", type: "email", label: "What is the email login for the Google Business page?", placeholder: "example@example.com" },
        { id: "googleBusinessAccess", type: "textarea", label: "Google Business Profile Access", description: "Please provide instructions on how to grant us access (e.g., invite our email as a manager). Do NOT share passwords." },
        { id: "facebookEmail", type: "email", label: "Facebook Login Email", placeholder: "example@example.com" },
        { id: "facebookAccess", type: "textarea", label: "Facebook Business Page Access", description: "Provide the email to invite as a Business Partner. Do NOT share passwords." },
        { id: "instagramHandle", type: "text", label: "Instagram Handle / Username" },
        { id: "tiktokHandle", type: "text", label: "TikTok Handle / Username" },
        { id: "googleAdsId", type: "text", label: "Google Ads Account ID", description: "Can be found at the top right of your Google Ads dashboard. Format: XXX-XXX-XXXX" },
        { id: "metaAdsId", type: "text", label: "Meta (Facebook) Ads Account ID", description: "Found in Meta Business Suite under Ad Accounts." },
      ],
    },
    {
      id: "goals-expectations",
      title: "Goals & Expectations",
      description: "Help us understand what success looks like for you.",
      fields: [
        { id: "goals", type: "textarea", label: "What are your top 3 goals for working with MyKohi?", required: true },
        { id: "expectations", type: "textarea", label: "What are your expectations from us in the first 90 days?" },
        { id: "additionalInfo", type: "textarea", label: "Is there anything else you'd like us to know?" },
      ],
    },
  ],
};

export default myKohiOnboardingTemplate;
